x-sap-action
SAP/openapi-specification pull request #20
Opened 2024-01-29 13:40 UTC by ralfhandl

2024-01-29 16:23 UTC, steffengoebel requested changes

2024-01-29 16:23 UTC, steffengoebel commented on sap-schemas/v2.0/README.md
> +- Used at: [Operation Object](https://spec.openapis.org/oas/v3.0.3#operation-object)
It should reference OpenAPI 2.0:
```suggestion
- Used at: [Operation Object](https://spec.openapis.org/oas/v2.0#operation-object)
```

2024-01-30 08:50 UTC, steffengoebel approved these changes

2024-02-06 13:40 UTC, ralfhandl commented on sap-schemas/v3.0/README.md
> +### `x-sap-operation-kind`
Rename to `x-sap-operation-intent`?

2024-02-06 13:41 UTC, ralfhandl commented on sap-schemas/v3.0/README.md
> +| `update-single`   | full or partial update of a single object, may allow "deep" update of a root object and its nested objects            | `PATCH`, `PUT` |
Do we want to distinguish between "update" and "upsert"?

2024-02-06 13:42 UTC, ralfhandl commented on sap-schemas/v3.0/README.md
> +| `update-single`   | full or partial update of a single object, may allow "deep" update of a root object and its nested objects            | `PATCH`, `PUT` |
Do we want to distinguish between "shallow" and "deep" update, or is this rather expressed by the request payload structure which has to allow nested objects for "deep" updates?

2024-03-21 17:10 UTC, steffengoebel requested changes

2024-03-21 17:10 UTC, steffengoebel commented on sap-extensions/v3.0-extensions.json
> +            "upsert-collection",
You removed "update-single" instead of "update-collection". Probably, copy&paste error.

2024-03-21 17:10 UTC, steffengoebel commented on sap-schemas/v2.0/README.md
> +| `update-single`   | full or partial update of a single object, may allow "deep" update of a root object and its nested objects            | `PATCH`, `PUT` |
`upsert-single` must be included from v3.0 README

2024-03-22 12:01 UTC, steffengoebel approved these changes

2024-03-22 12:05 UTC, pavelkornev approved these changes

2024-03-26 07:40 UTC, merged