Adding DPP-related annotations to OpenAPI spec.
SAP/openapi-specification pull request #30
Opened 2024-09-20 14:37 UTC by sthesse

The processing of personal data is key in business processes. Data Protection and Privacy related annotations enable consumers of APIs to identify potential entities and fields with personal data. Based on existing personal data annotations like in ODATA, the PR extends OpenAPI, with DPP annotations. The consumer of APIs can use the proposed DPP annotations to fulfil the requirements from data privacy regulations.

2024-09-23 11:43 UTC, ralfhandl requested changes

2024-09-23 11:43 UTC, ralfhandl commented on sap-schemas/v3.0/schema.json
> +          "description": "Role of the data subjects in this set (e.g. employee, customer). Values are application-specific. Can be a static value or a Path expression If the role varies per entity"
```suggestion
          "description": "Role of the data subjects in this set (e.g. employee, customer). Values are application-specific."
```
OpenAPI does not allow Path expressions, we would have to define how these are expressed if they are needed.

2024-09-23 11:43 UTC, ralfhandl commented on sap-schemas/v3.0/schema.json
> +          "description": "Language-dependent description of the role of the data subjects in this set (e.g. employee, customer). Values are application-specific. Can be a static value or a Path expre
```suggestion
          "description": "Language-dependent description of the role of the data subjects in this set (e.g. employee, customer). Values are application-specific."
```

2024-09-23 11:43 UTC, ralfhandl commented on sap-schemas/v3.0/schema.json
> +          "description": "Primary meaning of the personal data contained in the annotated property. Changes to values of annotated properties are tracked in the audit log. Use this annotation also on
```suggestion
          "description": "Primary meaning of the personal data contained in the annotated property. Changes to values of annotated properties are tracked in the audit log. Use this annotation also on fields that are already marked as contact or address data. Properties annotated with x-sap-dpp-fieldSemantics need not be additionally annotated with x-sap-dpp-isPotentiallyPersonal.",
```

2024-09-23 11:43 UTC, ralfhandl commented on sap-schemas/v3.0/schema.json
> +          "description": "Property contains potentially personal data.Properties annotated with x-sap-dpp-fieldSemantics need not be additionally annotated with this extension."
```suggestion
          "description": "Property contains potentially personal data. Properties annotated with x-sap-dpp-fieldSemantics need not be additionally annotated with this extension."
```

2024-09-23 11:43 UTC, ralfhandl commented on sap-schemas/v3.0/schema.json
Comments on this file also apply to the other three files, I just don't like to repeat myself.

2024-09-24 09:45 UTC, pavelkornev requested changes

2024-09-24 09:45 UTC, pavelkornev commented on sap-extensions/v2.0-extensions.json
> +        "x-sap-dpp-entitySemantics": {
We have a convention for extension fields names that they must follow kebab-case-notation.

There are some old fields with camelCase notation, those are exceptions due to historical reasons.

2024-09-24 11:27 UTC, pavelkornev commented
@sthesse aren't fields the same for OpenAPI v2 and OpenAPI v3? If so, please place them in https://github.com/SAP/openapi-specification/blob/main/sap-extensions/extensions.json, no need to duplicate content.

2024-09-28 20:43 UTC, pavelkornev approved these changes

2024-09-30 07:42 UTC, ralfhandl approved these changes

2024-09-30 08:18 UTC, merged